#!/usr/bin/env bash
# scripts/gen-testnet-env.sh
# Generates 10 fresh EOAs (1 deployer + 5 signers + bridge operator + poster
# + human guardian) and prints a .env block ready to paste into deploy/.env.
# Uses `cast wallet new` from Foundry — install if missing:
#   curl -L https://foundry.paradigm.xyz | bash && foundryup
#
# IMPORTANT: for TESTNETS ONLY. For mainnet, generate keys on an air-gapped
# machine or an HSM and NEVER let the deployer co-locate with role keys.
set -euo pipefail

if ! command -v cast >/dev/null 2>&1; then
  echo "error: cast not found. Install Foundry first:" >&2
  echo "  curl -L https://foundry.paradigm.xyz | bash && foundryup" >&2
  exit 1
fi

gen() {
  # cast wallet new output looks like:
  #   Successfully created new keypair.
  #   Address:     0x...
  #   Private key: 0x...
  local out
  out=$(cast wallet new)
  local addr key
  addr=$(echo "$out" | awk '/Address:/ {print $2}')
  key=$(echo "$out" | awk '/Private key:/ {print $3}')
  printf "%s|%s\n" "$addr" "$key"
}

IFS='|' read -r DEPLOYER_ADDR DEPLOYER_KEY     <<<"$(gen)"
IFS='|' read -r SIGNER_1_ADDR SIGNER_1_KEY     <<<"$(gen)"
IFS='|' read -r SIGNER_2_ADDR SIGNER_2_KEY     <<<"$(gen)"
IFS='|' read -r SIGNER_3_ADDR SIGNER_3_KEY     <<<"$(gen)"
IFS='|' read -r SIGNER_4_ADDR SIGNER_4_KEY     <<<"$(gen)"
IFS='|' read -r SIGNER_5_ADDR SIGNER_5_KEY     <<<"$(gen)"
IFS='|' read -r BRIDGE_OP_ADDR BRIDGE_OP_KEY   <<<"$(gen)"
IFS='|' read -r POSTER_ADDR POSTER_KEY         <<<"$(gen)"
IFS='|' read -r GUARDIAN_ADDR GUARDIAN_KEY     <<<"$(gen)"

cat <<EOF
# ---------------------------------------------------------------------------
# Generated by scripts/gen-testnet-env.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# PASTE into deploy/.env (gitignored) — TESTNET ONLY.
# Fund the deployer on Base Sepolia + OP Sepolia (see docs/deploy-live.md).
#
# Full private keys are below so you can bootstrap without an external secrets
# manager during early testing. Rotate to an HSM / KMS before mainnet.
# ---------------------------------------------------------------------------
DEPLOYER_PRIVATE_KEY=$DEPLOYER_KEY      # → $DEPLOYER_ADDR

DAES_SIGNER_1=$SIGNER_1_ADDR
DAES_SIGNER_2=$SIGNER_2_ADDR
DAES_SIGNER_3=$SIGNER_3_ADDR
DAES_SIGNER_4=$SIGNER_4_ADDR
DAES_SIGNER_5=$SIGNER_5_ADDR
DAES_BRIDGE_OPERATOR=$BRIDGE_OP_ADDR
DAES_POSTER=$POSTER_ADDR
DAES_HUMAN_GUARDIAN=$GUARDIAN_ADDR

# Matching private keys (stash in a password manager, do NOT commit):
#   DAES_SIGNER_1_KEY=$SIGNER_1_KEY
#   DAES_SIGNER_2_KEY=$SIGNER_2_KEY
#   DAES_SIGNER_3_KEY=$SIGNER_3_KEY
#   DAES_SIGNER_4_KEY=$SIGNER_4_KEY
#   DAES_SIGNER_5_KEY=$SIGNER_5_KEY
#   DAES_BRIDGE_OPERATOR_KEY=$BRIDGE_OP_KEY
#   DAES_POSTER_KEY=$POSTER_KEY
#   DAES_HUMAN_GUARDIAN_KEY=$GUARDIAN_KEY
EOF
